func_name: CEntitySystem_AddRefKeyValues
func_va: '0x1812201d0'
func_rva: '0x12201d0'
func_size: '0x57'
func_sig: 40 53 48 83 EC ?? 66 FF 42 ??
vtable_name: CEntitySystem_vtable
vfunc_offset: '0x38'
vfunc_index: 7
