func_name: CEntitySystem_ReleaseKeyValues
func_va: '0x18124fe90'
func_rva: '0x124fe90'
func_size: '0x7a'
func_sig: 40 53 48 83 EC ?? 80 7A ?? ??
vtable_name: CEntitySystem_vtable
vfunc_offset: '0x40'
vfunc_index: 8
