#!/usr/bin/env python3
"""Extract callbacks registered by GameStateAPI_RegisterAPIs."""

from ida_preprocessor_scripts._register_api_callbacks import (
    preprocess_register_api_callbacks_skill,
)


SOURCE_YAML_STEM = "GameStateAPI_RegisterAPIs"

API_NAMES = [
    "IsLatched",
    "GetPlayerSlot",
    "GetPlayerName",
    "GetPlayerXuidStringFromPlayerSlot",
    "GetLocalPlayerXuid",
    "GetLocalOrInEyePlayerXuid",
    "GetHudPlayerXuid",
    "GetPlayerTeamName",
    "GetPlayerTeamNumber",
    "GetCoachingTeamNumber",
    "GetAssociatedTeamNumber",
    "IsPlayerConnected",
    "IsPlayerAlive",
    "GetPlayerPing",
    "GetPlayerKills",
    "GetPlayerRoundKills",
    "GetPlayerAssists",
    "GetPlayerDeaths",
    "GetPlayerMVPs",
    "GetPlayerMoney",
    "GetPlayerScore",
    "GetPlayerClanTag",
    "GetPlayerActiveCoinRank",
    "GetPlayerCompetitiveRankType",
    "GetPlayerCompetitiveRanking",
    "GetPlayerCompetitiveWins",
    "GetPlayerPremierRankStatsObject",
    "GetPlayerDisplayFlairItem",
    "GetPlayerStatus",
    "IsFakePlayer",
    "GetPlayerActiveWeaponItemId",
    "IsXuidValid",
    "GetPlayerVoiceVolume",
    "SetPlayerVoiceVolume",
    "GetMapsInMapGroup",
    "GetMapDisplayNameToken",
    "GetMapsInCurrentMapGroup",
    "GetPlayerLifetime",
    "GetPlayerColor",
    "GetPlayerXpLevel",
    "GetPlayerXpTrailLevel",
    "GetPlayerCommendsLeader",
    "GetPlayerCommendsTeacher",
    "GetPlayerCommendsFriendly",
    "HasCommunicationAbuseMute",
    "HasCommunicationBan",
    "ShouldShowHudElements",
    "IsQueuedMatchmaking",
    "GetKickTargets",
    "GetPlayerCharacterItemID",
    "GetCharacterDefaultCheerByXuid",
    "GetCharacterDefaultDefeatByXuid",
    "ArePlayersEnemies",
    "GetCSGOGameUIStateName",
    "IsLocalPlayerPlayingMatch",
    "IsConnectedOrConnectingToServer",
    "AreTeamsPlayingSwitchedSides",
    "AreTeamsPlayingSwitchedSidesInRound",
    "IsReportCategoryEnabledForSelectedPlayer",
    "SubmitPlayerReport",
    "SubmitServerReport",
    "QueryServersForCommendation",
    "GetCommendationTokensAvailable",
    "GetMyCommendationsJSOForUser",
    "SubmitCommendation",
    "IsSelectedPlayerMuted",
    "ToggleMute",
    "GetCrosshairCode",
    "IsDemoOrHltv",
    "IsOverwatch",
    "IsLocalPlayerWatchingOwnDemo",
    "IsLocalPlayerHLTV",
    "IsHLTVAutodirectorOn",
    "SetCasterIsCameraman",
    "SetCasterIsHeard",
    "SetCasterControlsXray",
    "SetCasterControlsUI",
    "GetServerName",
    "GetMapName",
    "GetTournamentEventStage",
    "GetGameModeInternalName",
    "GetGameModeImagePath",
    "GetGameModeName",
    "GetViewerCount",
    "GetMapBSPName",
    "IsQueuedMatchmakingMode_Team",
    "HasHalfTime",
    "GetPlayerModel",
    "GetAllPlayersMatchDataJSO",
    "GetPlayerDataJSO",
    "GetTimeDataJSO",
    "GetScoreDataJSO",
    "GetPlayerStatsJSO",
    "GetMatchInfoJSO",
    "GetMatchEndWinDataJSO",
    "GetAccoladeLocalizationString",
    "GetTeamClanName",
    "GetTeamLogoImagePath",
    "GetTeamFlagImagePath",
    "GetTeamTotalPlayerCount",
    "GetTeamLivingPlayerCount",
    "GetTeamNextRoundLossBonus",
    "GetActiveQuestID",
    "GetAnnotationsViewingLevel",
    "BIsLocalServerHost",
]

TARGET_SPECS = [{"api_name": api_name, "target_name": f"GameStateAPI_{api_name}"} for api_name in API_NAMES]

TARGET_FUNCTION_NAMES = [spec["target_name"] for spec in TARGET_SPECS]

GENERATE_YAML_DESIRED_FIELDS = [
    (
        target_name,
        [
            "func_name",
            "func_sig",
            "func_sig_allow_across_function_boundary:true",
            "func_va",
            "func_rva",
            "func_size",
        ],
    )
    for target_name in TARGET_FUNCTION_NAMES
]


async def preprocess_skill(
    session,
    skill_name,
    expected_outputs,
    old_yaml_map,
    new_binary_dir,
    platform,
    image_base,
    llm_config=None,
    debug=False,
):
    """Extract all named API callbacks from the registrar function."""
    _ = skill_name, old_yaml_map, llm_config
    return await preprocess_register_api_callbacks_skill(
        session=session,
        expected_outputs=expected_outputs,
        new_binary_dir=new_binary_dir,
        platform=platform,
        image_base=image_base,
        source_yaml_stem=SOURCE_YAML_STEM,
        target_specs=TARGET_SPECS,
        generate_yaml_desired_fields=GENERATE_YAML_DESIRED_FIELDS,
        search_window_after_xref=96,
        search_window_before_call=128,
        debug=debug,
    )
