import js from '@eslint/js'
import globals from 'globals'
import reactHooks from 'eslint-plugin-react-hooks'
import reactRefresh from 'eslint-plugin-react-refresh'
import tseslint from 'typescript-eslint'
import { globalIgnores } from 'eslint/config'

export default tseslint.config([
  globalIgnores(['dist']),
  {
    files: ['**/*.mjs'],
    languageOptions: {
      ecmaVersion: 2023,
      globals: globals.node,
    },
  },
  {
    files: ['**/*.{ts,tsx}'],
    extends: [
      js.configs.recommended,
      tseslint.configs.recommended,
      reactHooks.configs['recommended-latest'],
      reactRefresh.configs.vite,
    ],
    languageOptions: {
      ecmaVersion: 2020,
      globals: globals.browser,
    },
  },
  {
    // Generated by `shadcn add`, which ships a component and its variant helper
    // (buttonVariants) from one file by design. Editing them to satisfy
    // fast-refresh would be undone by the next `add --overwrite`, so the rule is
    // relaxed here instead. It stays on everywhere else.
    files: ['src/ui/shadcn/**/*.{ts,tsx}'],
    rules: { 'react-refresh/only-export-components': 'off' },
  },
  {
    // Feature code goes through src/ui: the old hand-rolled `.btn` class and the
    // silent clipboard call were both replaced there, and these keep them from
    // coming back one call site at a time. A raw <button> is still fine for
    // things that are not buttons in look - a card, a row, a link-styled action.
    files: ['src/**/*.{ts,tsx}'],
    ignores: ['src/ui/**', 'src/**/*.test.{ts,tsx}'],
    rules: {
      'no-restricted-syntax': [
        'error',
        {
          selector: "JSXAttribute[name.name='className'] > Literal[value=/(^|\\s)btn(\\s|$)/]",
          message: 'Use <Button> from ui/primitives (or buttonClass from ui/buttonStyle for a non-button element).',
        },
        {
          selector: "MemberExpression[object.object.name='navigator'][object.property.name='clipboard'][property.name='writeText']",
          message: 'Use copyText from ui/clipboard: it reports success and failure instead of failing silently.',
        },
      ],
    },
  },
])
