func_name: CEngineServer_ClientCommandKeyValues
func_va: '0x6b5b80'
func_rva: '0x6b5b80'
func_size: '0x2e8'
func_sig: 55 48 89 E5 41 57 41 56 41 55 41 54 53 48 81 EC ?? ?? ?? ?? 4C 8B 3D ?? ?? ?? ??
vtable_name: CEngineServer_vtable
vfunc_offset: '0x248'
vfunc_index: 73
